Repository sky-ecosystem/next-gen-atlas, pull requests merged in 2025-06, with the labels that each got.

#4 add 2025-05-29 spell changes
  Sky Atlas/Sky Atlas.html
Labels: active-data-update, executive vote paramater updates

#11 cleanup of article and preamble sections
  Sky Atlas/Sky Atlas.html
Labels: enhancement, cleanup

#12 governance scope cleanup
  Sky Atlas/Sky Atlas.html
Labels: cleanup

#14 Derecognize ADs that failed to migrate
  Sky Atlas/Sky Atlas.html
Labels: delegates, active-data-update

#6 Update Multiple ADs
  Sky Atlas/Sky Atlas.html
Labels: delegates, active-data-update

#15 2025-06-16 weekly atlas edit proposal
  Sky Atlas/Sky Atlas.html
Labels: atlas edit, weekly proposal edit

#17 Cleanup multiple scopes and artifacts
  Sky Atlas/Sky Atlas.html
Labels: cleanup

#7 AEP-11: Edit
  Sky Atlas/Sky Atlas.html
Labels: atlas edit, monthly proposal edit

#18 Weekly Cycle Atlas Edit 2025-06-23
  Sky Atlas/Sky Atlas.html
Labels: atlas edit, weekly proposal edit

#19 2025-06-26 spell changes
  Sky Atlas/Sky Atlas.html
Labels: active-data-update, executive vote paramater updates
